#!/usr/bin/env bash
  pbj-liason() {
	# if arg1 starts with dash, run in this shell
	if [[ ${1:0:1} == "-" ]]; then
		/home/michael/projects/Python/scripts/pbj/pbj.py "$@"
		return 0
	fi
	# if no dash, first set this shell's terminal
	# width. This is so that the subsequent subshell
	# call gets the width of the terminal right.
	terminal_width=$(tput cols)
	/home/michael/projects/Python/scripts/pbj/pbj.py "--set-term-width" $terminal_width
	# then if successful, grab the output by calling it in a subshell
	if [[ $? -eq 0 ]]; then
	    pbj_output="$(/home/michael/projects/Python/scripts/pbj/pbj.py $@)"
	    if [ -d "$pbj_output" ]; then
		    # os.chdir([arg]) won't change dir in
		    # *this* shell, so use a bash wrapper.
		    cd "$pbj_output"
	    else
		    echo "$pbj_output" 
	    fi
	fi
  }
